#!/bin/bash
set -e

# ============================================
# COMPONENT EXTRACT WORKFLOW
# Extracts grabbed element into reusable component
# Auto-detects .grabbed_element if not provided
# ============================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/_lib/common.sh"

ELEMENT_FILE="${1:-.grabbed_element}"
OUTPUT_DIR=".workflow_output"
OUTPUT_FILE="$OUTPUT_DIR/component-extraction.md"
CONTEXT_FILE="$OUTPUT_DIR/grabby-context.md"

ensure_dir "$OUTPUT_DIR"

if [[ ! -f "$ELEMENT_FILE" ]]; then
    error "No grabbed element found. Add ?grab=true to URL and grab an element first."
fi

is_recently_grabbed() {
    local max_age_seconds="${1:-300}"
    if [[ ! -f "$ELEMENT_FILE" ]]; then
        return 1
    fi
    local file_age=$(($(date +%s) - $(stat -f %m "$ELEMENT_FILE" 2>/dev/null || stat -c %Y "$ELEMENT_FILE")))
    [[ $file_age -lt $max_age_seconds ]]
}

generate_grabby_context() {
    local selector=$(jq -r '.selector' "$ELEMENT_FILE" 2>/dev/null || echo "unknown")
    local tag=$(jq -r '.tagName' "$ELEMENT_FILE" 2>/dev/null || echo "unknown")
    local classes=$(jq -r '.className' "$ELEMENT_FILE" 2>/dev/null || echo "none")
    local text=$(jq -r '.innerText' "$ELEMENT_FILE" 2>/dev/null | head -c 100 || echo "")
    local width=$(jq -r '.rect.width' "$ELEMENT_FILE" 2>/dev/null || echo "0")
    local height=$(jq -r '.rect.height' "$ELEMENT_FILE" 2>/dev/null || echo "0")

    cat > "$CONTEXT_FILE" <<EOF
# GRABBY TOOLS CONTEXT

**Generated**: $(timestamp)
**Source**: component-extract.sh

## Element

- **Tag**: \`$tag\`
- **Selector**: \`$selector\`
- **Classes**: \`$classes\`
- **Dimensions**: ${width}x${height}px

**Text**: "$text"

## Workflow

**Component Extract** - Converting element to reusable React/Vue component.

EOF
    log "Context generated: $CONTEXT_FILE"
}

main() {
    log "Component Extract Workflow started"

    if ! is_recently_grabbed 300; then
        warn "Element was grabbed more than 5 minutes ago"
        info "Consider grabbing a fresh element"
    fi

    generate_grabby_context

    local selector=$(get_element_selector "$ELEMENT_FILE")
    local tag=$(get_element_tag "$ELEMENT_FILE")
    local classes=$(get_element_classes "$ELEMENT_FILE")
    local styles=$(get_element_styles "$ELEMENT_FILE")

    log "Extracting: $tag ($selector)"

    local component_name=$(echo "$classes" | sed 's/[^a-zA-Z0-9]//g' | sed 's/\(.\)\([A-Z]\)/\1-\2/g' | tr '[:upper:]' '[:lower:]')
    [[ -z "$component_name" ]] && component_name="${tag,,}-component"

    local component_name_pascal=$(echo "$component_name" | sed -E 's/(^|-)([a-z])/\U\2/g')

    cat > "$OUTPUT_FILE" <<EOF
# Component Extraction

**Generated**: $(timestamp)

## Source Element

- **Tag**: \`$tag\`
- **Selector**: \`$selector\`
- **Classes**: \`$classes\`

## Suggested Component Name

\`$component_name_pascal\` (PascalCase) or \`$component_name\` (kebab-case)

## Component Structure

### React/Next.js

\`\`\`tsx
// components/$component_name.tsx
import React from 'react';

interface ${component_name_pascal}Props {
  children?: React.ReactNode;
  className?: string;
}

export function $component_name_pascal({ children, className = '' }: ${component_name_pascal}Props) {
  return (
    <$tag className=\"\`$classes \${className}\`\">
      {children}
    </$tag>
  );
}
\`\`\`

### Vue

\`\`\`vue
<!-- components/$component_name.vue -->
<template>
  <$tag :class="classes">
    <slot />
  </$tag>
</template>

<script setup lang="ts">
interface Props {
  className?: string;
}

const props = withDefaults(defineProps<Props>(), {
  className: ''
});

const classes = computed(() => \`$classes \${props.className}\`);
</script>
\`\`\`

## Current Styles

\`\`\`json
$styles
\`\`\`

## Extraction Checklist

- [ ] Create component file
- [ ] Extract styles to CSS module or Tailwind
- [ ] Define prop interface
- [ ] Add TypeScript types
- [ ] Handle variants (hover, active, disabled)
- [ ] Add accessibility attributes
- [ ] Write component tests
- [ ] Update documentation
- [ ] Replace original element with component

## Usage Example

\`\`\`tsx
import { $component_name_pascal } from '@/components/$component_name';

function MyPage() {
  return (
    <$component_name_pascal>
      Content here
    </$component_name_pascal>
  );
}
\`\`\`

---

*Generated by Grabby Tools - Component Extract Workflow*
EOF

    log "Extraction guide saved to: $OUTPUT_FILE"

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  COMPONENT EXTRACTION COMPLETE"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Element: $tag"
    echo "Component: $component_name_pascal"
    echo ""
    echo "📄 Guide: $OUTPUT_FILE"
    echo "📄 Context: $CONTEXT_FILE"
    echo ""

    echo "$OUTPUT_FILE"
}

main "$@"
