#!/bin/bash
set -e

# ============================================
# STYLE REFACTOR WORKFLOW
# Converts inline/CSS styles to Tailwind
# Auto-detects .grabbed_element if not provided
# ============================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/_lib/common.sh"

ELEMENT_FILE="${1:-.grabbed_element}"
OUTPUT_DIR=".workflow_output"
OUTPUT_FILE="$OUTPUT_DIR/style-refactor.md"
CONTEXT_FILE="$OUTPUT_DIR/grabby-context.md"

ensure_dir "$OUTPUT_DIR"

if [[ ! -f "$ELEMENT_FILE" ]]; then
    error "No grabbed element found. Add ?grab=true to URL and grab an element first."
fi

is_recently_grabbed() {
    local max_age_seconds="${1:-300}"
    if [[ ! -f "$ELEMENT_FILE" ]]; then
        return 1
    fi
    local file_age=$(($(date +%s) - $(stat -f %m "$ELEMENT_FILE" 2>/dev/null || stat -c %Y "$ELEMENT_FILE")))
    [[ $file_age -lt $max_age_seconds ]]
}

generate_grabby_context() {
    local selector=$(jq -r '.selector' "$ELEMENT_FILE" 2>/dev/null || echo "unknown")
    local tag=$(jq -r '.tagName' "$ELEMENT_FILE" 2>/dev/null || echo "unknown")
    local classes=$(jq -r '.className' "$ELEMENT_FILE" 2>/dev/null || echo "none")
    local text=$(jq -r '.innerText' "$ELEMENT_FILE" 2>/dev/null | head -c 100 || echo "")
    local width=$(jq -r '.rect.width' "$ELEMENT_FILE" 2>/dev/null || echo "0")
    local height=$(jq -r '.rect.height' "$ELEMENT_FILE" 2>/dev/null || echo "0")

    cat > "$CONTEXT_FILE" <<EOF
# GRABBY TOOLS CONTEXT

**Generated**: $(timestamp)
**Source**: style-refactor.sh

## Element

- **Tag**: \`$tag\`
- **Selector**: \`$selector\`
- **Classes**: \`$classes\`
- **Dimensions**: ${width}x${height}px

**Text**: "$text"

## Workflow

**Style Refactor** - Converting inline styles to Tailwind CSS.

EOF
    log "Context generated: $CONTEXT_FILE"
}

main() {
    log "Style Refactor Workflow started"

    if ! is_recently_grabbed 300; then
        warn "Element was grabbed more than 5 minutes ago"
        info "Consider grabbing a fresh element"
    fi

    generate_grabby_context

    local selector=$(get_element_selector "$ELEMENT_FILE")
    local tag=$(get_element_tag "$ELEMENT_FILE")
    local styles=$(get_element_styles "$ELEMENT_FILE")

    log "Refactoring styles for: $tag ($selector)"

    local style_list=$(echo "$styles" | jq -r 'to_entries | map("- **\(.key)**: \(.value)") | join("\n")')

    cat > "$OUTPUT_FILE" <<EOF
# Style Refactor

**Generated**: $(timestamp)

## Element

- **Tag**: \`$tag\`
- **Selector**: \`$selector\`

## Current Styles

\`\`\`json
$styles
\`\`\`

## Style Breakdown

$style_list

## Tailwind Conversion

### Suggested Approach

| CSS Property | Tailwind Class |
|--------------|----------------|
| color | text-[value] |
| background-color | bg-[value] |
| padding | p-[value] / px-[value] py-[value] |
| margin | m-[value] / mt-[value] mb-[value] |
| width | w-[value] |
| height | h-[value] |
| border-radius | rounded-[value] |
| box-shadow | shadow-[value] |
| font-size | text-[value] |
| font-weight | font-[value] |

### Common Conversions

\`\`\`css
/* padding: 32px; */
padding: 32px;

/* Tailwind: */
class="p-8"  /* 32px = 8 * 4px */
class="p-6 md:p-8"  /* responsive */

/* background-color: rgb(250, 250, 250); */
background-color: rgb(250, 250, 250);

/* Tailwind: */
class="bg-[#FAFAFA]"
class="bg-gray-50"

/* color: oklch(0.21 0.034 264.665); */
color: oklch(0.21 0.034 264.665);

/* Tailwind: */
class="text-gray-900"
class="text-[#1a1a1a]"
\`\`\`

## Refactoring Steps

1. **Identify CSS properties** to convert
2. **Match to Tailwind classes** using table above
3. **Configure tailwind.config.js** for custom values:
   \`\`\`js
   module.exports = {
     theme: {
       extend: {
         colors: {
           primary: '#your-color',
         },
         spacing: {
           '128': '32px',
         },
       },
     },
   }
   \`\`\`
4. **Add responsive variants**: sm:, md:, lg:, xl:
5. **Add state variants**: hover:, focus:, active:, disabled:
6. **Test across viewports**

## Before/After

### Before
\`\`\`html
<$tag style="$(echo "$styles" | jq -r 'to_entries | map("\(.key): \(.value)") | join("; ")')">
</$tag>
\`\`\`

### After
\`\`\`html
<$tag class="p-8 bg-gray-50 text-gray-900">
</$tag>
\`\`\`

## Tailwind Config (if needed)

If using custom values from the styles:

\`\`\`js
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      colors: {
        // Extract from computed styles
      },
      spacing: {
        // Custom spacing if needed
      },
    },
  },
};
\`\`\`

---

*Generated by Grabby Tools - Style Refactor Workflow*
EOF

    log "Refactor guide saved to: $OUTPUT_FILE"

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  STYLE REFACTOR COMPLETE"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Element: $tag"
    echo "Styles converted: $(echo "$styles" | jq 'keys | length') properties"
    echo ""
    echo "📄 Guide: $OUTPUT_FILE"
    echo "📄 Context: $CONTEXT_FILE"
    echo ""

    echo "$OUTPUT_FILE"
}

main "$@"
